## Append samples of your project ##
resources:
- oadp_v1alpha1_nonadminbackup.yaml
- oadp_v1alpha1_nonadminrestore.yaml
- oadp_v1alpha1_nonadminbackupstoragelocation.yaml
- oadp_v1alpha1_nonadminbackupstoragelocationapprovalrequest.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
